### ISSUE TITLE
Attester Slashing 5116

### ISSUE THREAD

**Issue by dankrad** [goerli/medalla#39]
https://medalla.beaconcha.in/validator/5116
Eth1 address: 0xf689d779d9108FAa0Ba447399Fb2477687923278

No proposed blocks, so no graffiti

**Comment by AlexSSD7** [comment]
<img width="414" alt="" src="https://user-images.githubusercontent.com/43043344/89332228-52729900-d693-11ea-92d0-16c91f64fe9b.png">

This guy (Lamboshi aka Nolan#0383) is also a mod at the ethstaker discord server.

**Comment by AlexSSD7** [comment]
I will DM him

**Comment by LamboshiNakaghini** [comment]
Whoa super sleuths nice find. I was just rushing to set up all 5 clients last night and was not careful about copy pasting keys between clients. Definitely will not be doing that on mainnet.
