### ISSUE TITLE
Proposer slashing 21768 21769 21770 21171

### ISSUE THREAD

**Issue by terencechain** [goerli/medalla#42]
Eth1 address: 0x3a15459851b5346677bf9f7d3f8b2a8233eadaad

Instead of having 1 validator client running 4 keys. The victim launched 4 validator clients running 4 keys on each client. With 4 validator clients, each validator client has its own protection DB so that didn't help. Lesson learned from this incident, we have to improve on documentations and add protection schemes around wallet designs. See tracking issue for more details

Tracking issue:
https://github.com/prysmaticlabs/prysm/issues/6948

Add lock file for wallets:
https://github.com/prysmaticlabs/prysm/pull/6952

**Comment by dankrad** [comment]
Thanks for adding this. Closing since reason is known.

**Comment by dankrad** [comment]
Actually I can't close, please close :)
