### ISSUE TITLE
Medalla Metamask interfacee

### ISSUE THREAD

**Issue by raunchy-mx** [goerli/medalla#44]
I am trying to use the Medalla Launchpad and am at the "CONNECT WALLET" page. Although Metamask shows that I am  connected to the Medalla Launchpad, on the CONNECT WALLET I am in a continuous cycle.  Is there a distinction between an Account and a Wallet in Metamask?

**Comment by q9f** [comment]
Hey, could you direct that question to the launchpad team? https://github.com/ethereum/eth2.0-deposit
