### ISSUE TITLE
Add Zinken ETH2.0 testnet Launchpad and Explorer

### ISSUE THREAD

**Issue by ongrid** [goerli/medalla#60]
Launchpad and chain explorer are up and running
* Launchpad [ethereum.org](https://zinken.launchpad.ethereum.org/)
* Chain Explorers [beaconcha.in](https://zinken.beaconcha.in/)

Can be added to
https://github.com/goerli/medalla/tree/master/zinken

**Comment by q9f** [comment]
:+1:
