### ISSUE TITLE
cann't visit medalla.launchpad.ethereum.org

### ISSUE THREAD

**Issue by OK0X** [goerli/medalla#67]
I cant visit [medalla.launchpad.ethereum.org](https://launchpad.ethereum.org/)  ,
<img width="927" alt="failed" src="https://user-images.githubusercontent.com/48879766/99942976-7e816980-2dab-11eb-8f2a-5dcc490885e0.png">

but [launchpad.ethereum.org](https://launchpad.ethereum.org/) is ok.
<img width="960" alt="ok" src="https://user-images.githubusercontent.com/48879766/99942989-84774a80-2dab-11eb-8171-70885788f035.png">

**Comment by Buttaa** [comment]
Medalla is not supported anymore, try https://pyrmont.launchpad.ethereum.org/

**Comment by OK0X** [comment]
thank you

**Comment by memolabed** [comment]
Tanks
